### ISSUE TITLE
Typescript error in store/index.ts

### ISSUE THREAD

**Issue by consciouscoder** [victorkvarghese/react-native-zustand-boilerplate#2]
Any idea what this Typescript error is and how to fix it? Thanks in advance!

<img width="885" alt="Screen Shot 2022-12-03 at 7 33 39 PM" src="https://user-images.githubusercontent.com/5483671/205438925-55b0e561-84fd-42ff-87b0-4299039ad094.png">

**Comment by shubhambattoo** [comment]
+1

**Comment by victorkvarghese** [comment]
Closed https://github.com/victorkvarghese/react-native-query-boilerplate/commit/22f95fa286082a284a2dbd0ecf7433c487b7925d
